# Reproducible Change Log

- Date: 2026-08-23

## History

### 1. Vulnerability remediation policy

- Reviewed the Go dependency graph and the existing dependency update.
- Found that the existing dependency update caused incompatibilities between generated OpenAPI code and `kin-openapi`.
- Initial `govulncheck` execution was blocked by compilation errors in generated code and indirect dependencies.
- Defined a remediation policy: migrate the generator and runtime together, regenerate source code, remove obsolete test dependencies, tidy modules, and rerun security checks.

### 2. OpenAPI source generation

- Executed the three source-generation commands from the README.
- The v1 generator was deprecated and generated code required `github.com/oapi-codegen/runtime`.

### 3. Dependency and generated-code migration

- Migrated from deprecated `github.com/deepmap/oapi-codegen` v1 to `github.com/oapi-codegen/oapi-codegen/v2` v2.8.0.
- Added maintained `runtime`, `nethttp-middleware`, and `testutil` modules.
- Replaced obsolete middleware imports in `main.go` and `main_test.go`.
- Removed the test dependency on the old generated example API and used the local OpenAPI types instead.
- Regenerated:
  - `petstore/openapi/oapi_types.gen.go`
  - `petstore/openapi/oapi_server.gen.go`
  - `petstore/openapi/oapi_spec.gen.go`
- Ran `go mod tidy`, which removed obsolete indirect dependencies.

### 4. Go toolchain security update

- `govulncheck` identified vulnerabilities in the Go standard library bundled with Go 1.26.1.
- Updated the required Go version in `go.mod` to `1.26.6`, which includes the applicable fixes.

### 5. README documentation

- Updated the three README generation commands to use the v2 CLI.
- Documented the Go version requirement, maintained modules, deprecated v1 module warning, dependency maintenance policy, and security verification commands.

### 6. Generated source removal

- Removed the three OpenAPI source files generated by codegen as a separate repository change.
- The removal was merged into `main` through pull request #4.
- Reproducing the application build now requires running the three generation commands documented in `README.md` before running the tests.

## Verification at migration stage

All checks completed successfully:

```text
go test ./...
go vet ./...
go mod verify
govulncheck ./...
```

`govulncheck` result: `No vulnerabilities found.`

The verification above applies to the migration state before the generated
source files were removed. After removal, `go test ./...` is expected to fail
until the generated sources are recreated.
