// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RXT48bufH9KgX+fsdOa2IvctApXo8XEJC1J5kkl7UPJbJaKoN/esiixoOBvntQ7NY/",
	"j9bGIkGwQC4zUotkvXr1qvj62dgUxhQpSjHLZ1PslgK2j+9yTlk/jDmNlIWpPbbJkf4fUg4oZmk4yutX",
	"pjPyNNL0lTaUzb4zgUrBTVs9/1gkc9yY/b4zmR4qZ3Jm+ct05mn9p+Nhaf2ZrOhZ7+nxjuQlnIjhWoDO",
	"CG6+H7jtvhZujoXefxjM8pdn8/+ZBrM0/7c48bWYyVrM2Pbd1+DYfc3Un364wtRXoNhdgfRpr8s4Dmkq",
	"QhS0DSIFZG+WBkcWwvDn8oibDeWek+lmdsz99Aze3K3g74TBdKZm3bQVGZeLxdmefWccFZt5FE7RLM0b",
	"KBhGT22zbFGgFiqAMJIUSZkAC2AE+jItkwSOQopFMgrBQCg1UwGOIFuCDyNFPel1fwNlJMsDW2yhOuPZ",
	"Uix0Kqt5M6LdErzqby4gl+Vi8fj42GP7uU95s5j3lsVfVm/fvb9/94dX/U2/leCbFiiH8mG4p7xjS9fy",
	"XrQlCy0Oiz/n7G5O03RmR7lMpPyxv+lv9OQ0UsSRzdK8bo86M6JsW/EXSpB+2ExauqT1byQ1xwLofWMS",
	"hpxCY6g8FaEwUa3fa6EMWyXZWioFJH2M7zFAIQc2RceBotQAVKSHn5EsRSwgFMaUoeCGRbhAwZEpdhDJ",
	"Qt6maGuBQuFsAQtgIOnhDUXCCCiwybhjh4B1U6kDtMBoq+e2tYe3NeOapWZIjhP4lCl0kHLETEAbEiBP",
	"M7pItgNbc6kF2IEnK7X0cFu5QGCQmkcuHYzV7zhi1liUkybdgXC07GoU2GHmWuBzLZJ6WEXYooWtgsBS",
	"CEaPQgiOrdSgdKymFtNc0PHIxXLcAEbRbE65e95Uj8fMxy1mkowHEnU9hOSpCBNwGCk7Vqb+yTsMU0Lo",
	"+aFiAMeozGQs8KC57cizQEwRJGVJWSnhgaI7Ru/hLiMViqIwKXI4Aag5IuySrzKiwI4iRVTAE7n6J2DN",
	"esYqnk4eKM+sD2jZc7kI0iLon+5UXwslOfSkhXWd8mgpo2hi+r+H+1pGio6VZY8qHpd8yp0qsJAVVXPL",
	"sklFs+5gR1u21SPooMuuBvC8ppx6+DnlNQNVLiG58zLoz03YHi1Hxv5jvCfX6lALDKTS82mdcltO6aSX",
	"XCXX0IN2RsB23Ew9F98B1YtemQoOvqoKVZs93G2xkPdTW4yU5+2N5FZcEhiwWl7XiW48xNF15/t35OfC",
	"8Y5yxu4ytHYJsOuObRh5ve3hHwIjeU9RqDxUgjGVStpHhxbqQanAQw9oyx2YPJx0SKvx2DUgR1HEGi1I",
	"5iKaC+xYkHr4qRZLQNJmgat87AGdE8WSp8wNzqTew4agWqnYpGNrKBgh4EZTJj9Xq4e/1mlrSF7rNlWP",
	"6qScE5TuOHoAq9UWmVbO4pzSnqUxj5hjL6pUtMDAsTtBmds2cuED4KIYLEt1rFBLQahyUNlcyCnSBWkt",
	"Xg9354VpzM0Yx0zCNZzNrUk0tTtTtw7e/qNecOoN2mW3cmZpfuLo9HZpl0ZWAiiXZjYurwrBjU59GNgL",
	"ZVg/GTUCZmkeKuWn0y2v60w3W7hmP4RCuW6OpgeYMz7p9yJP7dJTq9J8zCWCgF846BCvYU0Z0gCZSvXS",
	"YOV2k/0KJs+B5QLUd33j/pPaoTLqYGnoX93cHDwPxcmWjaOfbcPic1GIz9fS/pZnmwzbV0TsX7ifkQQO",
	"YCZvNGD18pvwfAvGZLKvBK6Rvow6WHUCH9eMqVzxEm8zoTRPFulR3cTBbDXjopfsBE+XqF/zPj2Se6HH",
	"N07laCYzSkV+TO7pP5bowSO/zPSORGWEzum/I2xzboolV9r/m7L4rhp+59Xfd5OlXDyz208i8CT0Ug7T",
	"c5VD4bjx1BSxRp2VadLF6hZKVdRXVHDbdk9C+OZYWt3qIBin6s1Y5iGgHvg0A9i9qOWvDYTrr0cvB8IP",
	"L7NWIBMK9zto1G97/snTH0tyLNTqtgMeTq7fJSoQk8AWd3Ty/23B2Cp09Ub58WnlflP1BhK7/a8V73+s",
	"bfV6pbw7lOHixfvwDt2fvYnq6+T+0/5fAQAA//9WyUg8mhEAAA==",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}

