// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FdPjxu58f0qBf5+x05rYi9y0ClejxcQkLUnmSSXtQ8lsloqg396yKLGg4G+e1Ds1j+P1sYiQbBALjNS",
	"i2S9evWq+PrZ2BTGFClKMctnU+yWAraP73JOWT+MOY2Uhak9tsmR/h9SDihmaTjK61emM/I00vSVNpTN",
	"vjOBSsFNWz3/WCRz3Jj9vjOZHipncmb5y3Tmaf2n42Fp/Zms6Fnv6fGO5CWciOFagM4Ibr4fuO2+Fm6O",
	"hd5/GMzyl2fz/5kGszT/tzjxtZjJWszY9t3X4Nh9zdSffrjC1Feg2F2B9GmvyzgOaSpCFLQNIgVkb5YG",
	"RxbC8OfyiJsN5Z6T6WZ2zP30DN7creDvhMF0pmbdtBUZl4vF2Z59ZxwVm3kUTtEszRsoGEZPbbNsUaAW",
	"KoAwkhRJmQALYAT6Mi2TBI5CikUyCsFAKDVTAY4gW4IPI0U96XV/A2UkywNbbKE649lSLHQqq3kzot0S",
	"vOpvLiCX5WLx+PjYY/u5T3mzmPeWxV9Wb9+9v3/3h1f9Tb+V4JsWKIfyYbinvGNL1/JetCULLQ6LP+fs",
	"bk7TdGZHuUyk/LG/6W/05DRSxJHN0rxujzozomxb8RdKkH7YTFq6pPVvJDXHAuh9YxKGnEJjqDwVoTBR",
	"rd9roQxbJdlaKgUkfYzvMUAhBzZFx4Gi1ABUpIefkSxFLCAUxpSh4IZFuEDBkSl2EMlC3qZoa4FC4WwB",
	"C2Ag6eENRcIIKLDJuGOHgHVTqQO0wGir57a1h7c145qlZkiOE/iUKXSQcsRMQBsSIE8zuki2A1tzqQXY",
	"gScrtfRwW7lAYJCaRy4djNXvOGLWWJSTJt2BcLTsahTYYeZa4HMtknpYRdiiha2CwFIIRo9CCI6t1KB0",
	"rKYW01zQ8cjFctwARtFsTrl73lSPx8zHLWaSjAcSdT2E5KkIE3AYKTtWpv7JOwxTQuj5oWIAx6jMZCzw",
	"oLntyLNATBEkZUlZKeGBojtG7+EuIxWKojApcjgBqDki7JKvMqLAjiJFVMATufonYM16xiqeTh4oz6wP",
	"aNlzuQjSIuif7lRfCyU59KSFdZ3yaCmjaGL6v4f7WkaKjpVljyoel3zKnSqwkBVVc8uySUWz7mBHW7bV",
	"I+igy64G8LymnHr4OeU1A1UuIbnzMujPTdgeLUfG/mO8J9fqUAsMpNLzaZ1yW07ppJdcJdfQg3ZGwHbc",
	"TD0X3wHVi16ZCg6+qgpVmz3cbbGQ91NbjJTn7Y3kVlwSGLBaXteJbjzE0XXn+3fk58LxjnLG7jK0dgmw",
	"645tGHm97eEfAiN5T1GoPFSCMZVK2keHFupBqcBDD2jLHZg8nHRIq/HYNSBHUcQaLUjmIpoL7FiQevip",
	"FktA0maBq3zsAZ0TxZKnzA3OpN7DhqBaqdikY2soGCHgRlMmP1erh7/WaWtIXus2VY/qpJwTlO44egCr",
	"1RaZVs7inNKepTGPmGMvqlS0wMCxO0GZ2zZy4QPgohgsS3WsUEtBqHJQ2VzIKdIFaS1eD3fnhWnMzRjH",
	"TMI1nM2tSTS1O1O3Dt7+o15w6g3aZbdyZml+4uj0dmmXRlYCKJdmNi6vCsGNTn0Y2AtlWD8ZNQJmaR4q",
	"5afTLa/rTDdbuGY/hEK5bo6mB5gzPun3Ik/t0lOr0nzMJYKAXzjoEK9hTRnSAJlK9dJg5XaT/Qomz4Hl",
	"AtR3feP+k9qhMupgaehf3dwcPA/FyZaNo59tw+JzUYjP19L+lmebDNtXROxfuJ+RBA5gJm80YPXym/B8",
	"C8Zksq8ErpG+jDpYdQIf14ypXPESbzOhNE8W6VHdxMFsNeOil+wET5eoX/M+PZJ7occ3TuVoJjNKRX5M",
	"7uk/lujBI7/M9I5EZYTO6b8jbHNuiiVX2v+bsviuGn7n1d93k6VcPLPbTyLwJPRSDtNzlUPhuPHUFLFG",
	"nZVp0sXqFkpV1FdUcNt2T0L45lha3eogGKfqzVjmIaAe+DQD2L2o5a8NhOuvRy8Hwg8vs1YgEwr3O2jU",
	"b3v+ydMfS3Is1Oq2Ax5Ort8lKhCTwBZ3dPL/bcHYKnT1RvnxaeV+U/UGErv9rxXvf6xt9XqlvDuU4eLF",
	"+/AO3Z+9ierr5P7T/l8BAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
