package domain

import (
	"github.com/opbls/scapo/petstore/openapi"
)

// Most of Entities are generated by oapi-codegen.
type (
	// Pet entity.
	Pet openapi.Pet
	// Pets entity.
	Pets []openapi.Pet
	// QueryCondition entity.
	QueryCondition map[string]interface{}
)
